export const events = {
  TICKET_CREATED: "TICKET_CREATED",
  TICKET_DELETED: "TICKET_DELETED",
  TICKET_UPDATED: "TICKET_UPDATED",
  IMPORTANT_TICKET_UPDATE: "IMPORTANT_TICKET_UPDATE",

  PROJECT_CREATED: "PROJECT_CREATED",
};
