import { Sidebar } from "@/components/layout/sidebar/Sidebar";
import { TopBar } from "@/components/layout/top-bar/TopBar";
import { AuthContextProvider } from "@/context/auth-context";
import { ProjectContextProvider } from "@/context/project-context";
import type { Metadata } from "next";
import "../globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="overflow-x-hidden">
        <AuthContextProvider>
          <ProjectContextProvider>
            <main className="flex items-stretch justify-stretch">
              <Sidebar />
              <TopBar width={240} />
              <div className="mt-[75px] bg-gray-200 grow p-10">
                <div>{children}</div>
              </div>
            </main>
          </ProjectContextProvider>
        </AuthContextProvider>
      </body>
    </html>
  );
}
